all: agent

agent: agent.o astar.o amidar_image.o escape_agent.o
	$(CXX) agent.o astar.o amidar_image.o escape_agent.o $(AGENTLDFLAGS) -o agent

agent.o: agent.cpp
	$(CXX) $(CFLAGS) -c agent.cpp -o agent.o

astar.o: astar.cpp
	$(CXX) $(CFLAGS) -c astar.cpp -o astar.o

amidar_image.o: amidar_image.cpp
	$(CXX) $(CFLAGS) -c amidar_image.cpp -o amidar_image.o

escape_agent.o: escape_agent.cpp
	$(CXX) $(CFLAGS) -c escape_agent.cpp -o escape_agent.o

clean:
	rm -rf agent agent.exe *.o
